=== Setup the Forge application

First thing to do is creating our application by using the `Forge CLI`:

[source,bash]
----
forge create random-user
----

This command shows you various templates to start a new Forge app.
Select `Custom UI`, then `jira-issue-panel` by using arrow keys, and press kbd:[Enter] :

----
Start with a template. Each template contains the required files to be a valid app.

? Select a category: Custom UI
? Select a template: jira-issue-panel

✔ Creating app...

ℹ Downloading template
ℹ Registering app
ℹ Creating environments
ℹ Installing dependencies

✔ Created cat-tachment

Your app is ready to work on, deploy, and install. We created 3 environments you can deploy to: development, staging, production.

Change to directory random-user to see your app files.
----

This template contains files which will be useful in the last part (Custom UI).
Now, if you navigate to the https://developer.atlassian.com/console/myapps/[Forge Developer Console], you should see your newly created app.

To continue the setup, go to the  `./static/hello-world/` folder, and run the following command:

[source, bash]
----
npm install
npm run build
----

This part is required to start your Forge app and will be explained later, in the Custom UI part.
Ignore it for now and go back to the top of your app directory (`cd ../..`).

Let's see files generated by the Forge CLI:

* `./src` folder which contains code relative to **Forge functions** and **UI Kit**
** `index.tsx` you can ignore its content for now (since it related to the issue view / Custom UI)
* `./static` same, you can ignore for now
* `manifest.yml` is the file describing your app

Let's focus on the `manifest.yml` file and its different parts:

[source, yaml]
----
modules:
  jira:issuePanel: <1>
    - key: random-user-hello-world-panel
      resource: main
      resolver:
        function: resolver
      viewportSize: medium
      title: random-user
      icon: https://developer.atlassian.com/platform/forge/images/issue-panel-icon.svg
  function: <2>
    - key: resolver
      handler: index.handler
resources: <3>
  - key: main
    path: static/hello-world/build
app: <4>
  id: ari:cloud:ecosystem::app/9513507c-5fa1-4e5e-8fee-a5d7ef17a07e
----
<1> `modules` are locations inside Atlassian products where your app can be displayed.
The current module allows our app to appear in the Jira issue.
<2> `function` allows you to define Javascript function as Forge functions.
They are used by `modules` entries to display content.
The `key` property is a unique identifier for the function, and the `handler` is the "path" to the function. Here, we ask the function `handler` from the file `./src/index.js`.
<3> `resources` are used by Custom UI (so, let's see this later)
<4> `app` is used to identify your app in the Atlassian Forge infrastructure.

[IMPORTANT]
====
* The indentation is really important in the YAML language
* If you copy manifest contents from this exercise, ensure to replace the `app.id` with the one generated when you created the application. Otherwise, you will have permission issues.
====

We will add other properties soon in this exercise.

[TIP]
.Resource
====
All available properties of the `manifest.yml` file can be found on the https://developer.atlassian.com/platform/forge/manifest-reference/[Forge Documentation].
====

Now, let's start creating our administration!